const lockers = [
    { id: 'Box1', command: 'deligramA', response: 97 },
    { id: 'Box2', command: 'deligramB', response: 98 },
    { id: 'Box3', command: 'deligramC', response: 99 },
    { id: 'Box4', command: 'deligramD', response: 100 },
    { id: 'Box5', command: 'deligramE', response: 101 },
    { id: 'Box6', command: 'deligramF', response: 102 },
    { id: 'Box7', command: 'deligramG', response: 103 },
    { id: 'Box8', command: 'deligramH', response: 104 },
    { id: 'Box9', command: 'deligramI', response: 105 },
    { id: 'Box10', command: 'deligramJ', response: 106 },
    { id: 'Box11', command: 'deligramK', response: 107 },
    { id: 'Box12', command: 'deligramL', response: 108 },
    { id: 'Box13', command: 'deligramM', response: 109 },
    { id: 'Box14', command: 'deligramN', response: 110 },
    { id: 'Box15', command: 'deligramO', response: 111 },
    { id: 'Box16', command: 'deligramP', response: 112 },
    { id: 'Box17', command: 'deligramQ', response: 113 },
    { id: 'Box18', command: 'deligramR', response: 114 },
    { id: 'Box19', command: 'deligramS', response: 115 },
    { id: 'Box20', command: 'deligramT', response: 116 },
    { id: 'Box21', command: 'deligramU', response: 117 },
    { id: 'Box22', command: 'deligramV', response: 118 },
    { id: 'Box23', command: 'deligramW', response: 119 },
    { id: 'Box24', command: 'deligramX', response: 120 },
    { id: 'Box25', command: 'deligramY', response: 121 },
    { id: 'Box26', command: 'deligramZ', response: 122 }
]

export default lockers